[Admin ] - Gab/list application integration
Bendomey/project-mfoni pull request #103
Opened 2024-11-07 09:08 UTC by gidoo5331

2024-11-07 10:16 UTC, Bendomey requested changes

2024-11-07 10:16 UTC, Bendomey commented on apps/admin/modules/creator-application/index.tsx
> +      sort: '-createdAt',
I don't think this api's sort feature works this way.

<img width="583" alt="Screenshot 2024-11-07 at 9 59 53 AM" src="https://github.com/user-attachments/assets/98207527-c1d6-44f5-9d41-5ac4b5136abf">

You could check the docs and update the   functionality

2024-11-07 10:50 UTC, Bendomey requested changes

2024-11-07 10:50 UTC, Bendomey commented on apps/admin/modules/creator-application/index.tsx
> +      sortBy: '-createdAt',
```suggestion
      sortBy: 'createdAt',
```

2024-11-07 10:59 UTC, Bendomey approved these changes

2024-11-07 11:00 UTC, merged

2024-11-08 13:49 UTC, arkhurst reviewed
👍🏽