[Admin] - Gab/approve application integration
Bendomey/project-mfoni pull request #106
Opened 2024-11-21 13:52 UTC by gidoo5331

When I click on approve I don't get any success or failed toast.

2024-11-21 19:14 UTC, arkhurst requested changes

2024-11-21 19:14 UTC, arkhurst commented on apps/admin/modules/creator-application/approve/index.tsx
> +      await mutateAsync(data!.id)
if data can be undefined, i think we should handle that error
maybe:

`
  if(!data?.id) {
    // handle error
  }
`

2024-11-21 19:14 UTC, arkhurst commented on apps/admin/modules/creator-application/approve/index.tsx
> +          { isLoading && (<Loader2Icon className="animate-spin" />)} Yes, Approve
None blocking: But I normally prefer

`{ isLoading ? <Loader2Icon className="animate-spin" /> : null }`

2024-11-22 23:37 UTC, Bendomey requested changes

2024-11-22 23:37 UTC, Bendomey commented on apps/admin/modules/creator-application/reject/index.tsx
> +  // };
why is this commented out?

2024-11-23 07:25 UTC, gidoo5331 commented on apps/admin/modules/creator-application/reject/index.tsx
> +  // };
Will do integration for reject in another PR, and I deleted the testData I was using before you gave me the Api.

2024-11-24 17:02 UTC, Bendomey approved these changes

2024-11-24 17:03 UTC, merged