[Admin ] - Gab/wallet-UI
Bendomey/project-mfoni pull request #129
Opened 2024-12-13 16:22 UTC by gidoo5331

![Screenshot from 2024-12-13 12-59-44](https://github.com/user-attachments/assets/928745b3-5552-4a77-843a-9a3f86f1290b)
![Screenshot from 2024-12-13 13-00-02](https://github.com/user-attachments/assets/54eae043-83d4-44bb-afde-bcec4c8be066)

2024-12-13 23:33 UTC, Bendomey requested changes
Will you integrate the wallet balance in a different PR?

2024-12-14 06:34 UTC, gidoo5331 commented
> Will you integrate the wallet balance in a different PR?

Yes

2024-12-14 07:41 UTC, arkhurst reviewed
code looks good 🚀

2024-12-14 11:20 UTC, Bendomey approved these changes

2024-12-14 11:20 UTC, merged