[Admin Portal] - Gab/list content
Bendomey/project-mfoni pull request #150
Opened 2024-12-31 15:23 UTC by gidoo5331

## Overview

Created content listing page

## Detailed Technical Change

Created a new page to view all contents
Added types for contents

## Testing Approach & Result

![Screenshot from 2024-12-31 15-11-18](https://github.com/user-attachments/assets/39013e8f-f1e7-44f0-b9bc-9dca15283e8a)

## Related Work

N/A

## Documentation

N/A

2024-12-31 15:59 UTC, arkhurst requested changes

2024-12-31 15:59 UTC, arkhurst commented on apps/admin/modules/content/index.tsx
> +          error={error ? new Error("Can't fetch contents") : undefined}
I see a potential issue here -  The error handling in the DataTable component is creating a new Error object every time it is rendered if there is an error. This can cause unnecessary re-renders and performance issues. Instead, the error should be handled in a way that it doesn't create a new object on every render.
A more efficient approach would be to define the error outside the JSX and pass it to the DataTable component. Here is a revised version of the lines:

2024-12-31 15:59 UTC, arkhurst commented on apps/admin/modules/content/index.tsx
> +        <DataTable
```suggestion
 
 const dataTableError = error ? new Error("Can't fetch contents") : undefined;

       <DataTable
  boxHeight={75}
  columns={columns}
  data={data?.rows ?? []}
  isDataLoading={isDataLoading}
  error={dataTableError}
  refetch={refetch}
  filterFields={filterFields}
  dataMeta={{
    total: data?.total ?? 0,
    page: currentPage,
    pageSize: CONTENTS_PER_PAGE,
    totalPages: data?.totalPages ?? 1,
  }}
>
```

2024-12-31 15:59 UTC, arkhurst commented on apps/admin/modules/content/index.tsx
> +          dataMeta={{
We might be re-using this object across various tables. We can actually create a global util that extracts and returns the object in this format. This is optional, but we can work on it if it's feasible.

2024-12-31 15:59 UTC, arkhurst commented on apps/admin/types/content/index.ts
> +	createdById: string
is it me of this doesn't look properly formatted?

2024-12-31 16:52 UTC, gidoo5331 commented on apps/admin/modules/content/index.tsx
> +          error={error ? new Error("Can't fetch contents") : undefined}
Alright, thanks, I'll change them.

2024-12-31 17:08 UTC, gidoo5331 commented on apps/admin/modules/content/index.tsx
> +          dataMeta={{
It can be done.

2025-01-01 10:25 UTC, arkhurst approved these changes

2025-01-01 10:26 UTC, merged