Save User PHone Number Feature
Bendomey/project-mfoni pull request #32
Opened 2024-01-19 17:54 UTC by noah-martey

2024-01-19 18:18 UTC, arkhurst commented on services/main/Configurations/SmsConfiguration.cs
> +            HttpResponseMessage response =
you having a linting error here

2024-01-19 18:28 UTC, noah-martey commented on services/main/Configurations/SmsConfiguration.cs
> +            HttpResponseMessage response =
Alright thanks

2024-01-19 19:24 UTC, Bendomey requested changes
First look was great. Just a couple of questions/fixes ;)

2024-01-19 19:24 UTC, Bendomey commented on services/main/Configurations/DatabaseSettings.cs
> +
Thanks for cleaning up my mess!

2024-01-19 19:24 UTC, Bendomey commented on services/main/Configurations/RedisDataBaseConfiguration.cs
> +        ConnectionMultiplexer redis = ConnectionMultiplexer.Connect("localhost");
```suggestion
        ConnectionMultiplexer redis = ConnectionMultiplexer.Connect(envName);
```

We might want to expose this as an env.... so that we can use remote redis when deploying!

2024-01-19 19:24 UTC, Bendomey commented on services/main/Configurations/SmsConfiguration.cs
> +            ""callback_url"": ""http://example.com/handle_callback/"",
```suggestion
```

We don't need callback_url now!

2024-01-19 19:24 UTC, Bendomey commented on services/main/Configurations/SmsConfiguration.cs
> +            ""app_secret"": ""xxyyxyxyxyxyxyxyxyxyxyxyzzz""
Env?

2024-01-19 19:24 UTC, Bendomey commented on services/main/Controllers/User.cs
> +    public async Task<OutputResponse<bool?>> SavePhoneNumber([FromBody] PhoneNumber userPhoneNumber)
```suggestion
    public async Task<OutputResponse<bool?>> SavePhoneNumber([FromBody] PhoneNumberInput userPhoneNumber)
```

We want to append the types with `Input` or `Output` so that we can easily differentiate two types when we see them.

Also, is this the structure? `{"phoneNumber": "string"}`? We'd want the frontend to submit an object as body =)

2024-01-19 19:24 UTC, Bendomey commented on services/main/Domains/UserMngmt/UserService.cs
> +            throw new Exception($"User with Id: {userId} not found");
For our error messages let's concatenate so that frontend can easily send good errors to users. We wouldn't want user's to see id's in error messages 😅.

In this case, we can do, `UserNotFound`

2024-01-19 19:24 UTC, Bendomey commented on services/main/Domains/UserMngmt/UserService.cs
> +        var phoneNumberId = Nanoid.Generate("1234567890", 5);
```suggestion
        var code = Nanoid.Generate("1234567890", 5);
```

I'm guessing copy/paste gone wrong?

2024-01-19 19:24 UTC, Bendomey commented on services/main/Domains/UserMngmt/UserService.cs
> +
We'll leave this for now until we get a better way to connect to redis centrally. With this method, it seems like it'll always connect when you hit the endpoint. If we connect it centrally, we wouldn't have to reconnect everytime we make a request to this endpoint.

2024-01-19 19:24 UTC, Bendomey commented on services/main/Domains/UserMngmt/UserService.cs
> +        _ = SmsConfiguration.SendSms(phoneNumber, $"Your number {phoneNumber} has been saved");
I'm not sure this is the right message we're sending to the users. Essentially, we want to send the code we generated to them so that they can use that to verify themselves on the platform. Use this message template I shared in the ticket desscription - https://trello.com/c/IUqEu9dh/24-api-endpoint-to-save-phone-number

2024-01-20 11:34 UTC, Bendomey commented on services/main/Controllers/User.cs
> +    [HttpPost("savePhoneNumber")]
This does not conform to what's in the ticket. Kindly double check the ticket for the right route dets =)

2024-01-20 12:10 UTC, noah-martey commented on services/main/Controllers/User.cs
> +    public async Task<OutputResponse<bool?>> SavePhoneNumber([FromBody] PhoneNumber userPhoneNumber)
Yes, it allows frontend to submit object as body.

2024-01-25 23:39 UTC, Bendomey commented
FYI: Since it's DI architecture, I just created configs for mongo and redis and then connected to it centrally. So now, we don't have to open a connection for each service/request

2024-01-25 23:39 UTC, Bendomey approved these changes

2024-01-25 23:40 UTC, merged