Refactored Creation of a Tag for A User
Bendomey/project-mfoni pull request #44
Opened 2024-02-14 11:48 UTC by noah-martey

2024-02-14 14:23 UTC, Bendomey requested changes

2024-02-14 14:23 UTC, Bendomey commented on services/main/Controllers/Tag.cs
> +    [HttpPost("create/tag")]
```suggestion
    [HttpPost]

```

You can learn somethings about API DESIGN here: https://swagger.io/resources/articles/best-practices-in-api-design/

2024-02-14 14:23 UTC, Bendomey commented on services/main/Domains/TagsMngmt/SaveTagsService.cs
>      }
Let's use the synchronous version for now. Unless you'd want to look into this https://stackoverflow.com/questions/19431494/how-to-use-await-in-a-loop#:~:text=The%20way%20you're%20using,ing%20them%20all%20with%20Task.

2024-02-14 14:23 UTC, Bendomey commented on services/main/Domains/TagsMngmt/SaveTagsService.cs
> +        inputTags.ToList().ForEach(async tag =>
This is the reason for the comment above, running a loop and await each step does not work. You can see in the url I sent earlier

2024-02-14 14:23 UTC, Bendomey commented on services/main/Domains/TagsMngmt/SaveTagsService.cs
> +                var newTag = await Create(new CreateTagInput { Name = tag }, "a_user_id");
What's `a_user_id` in here? I think you might want to expect a user_id in ResolveTags too, so you pass it down

2024-02-14 14:23 UTC, Bendomey commented on services/main/Domains/TagsMngmt/SaveTagsService.cs
> +        return Task.FromResult(tags);
Maybe this fixes the problem I was pointing to earlier? Lemme know :)

2024-02-14 16:31 UTC, noah-martey commented on services/main/Domains/TagsMngmt/SaveTagsService.cs
> +                var newTag = await Create(new CreateTagInput { Name = tag }, "a_user_id");
Yes, but for now, since I modified the Create function I didn't want the build to break, so I used that as a reference for userId for the future

2024-02-14 16:34 UTC, noah-martey commented on services/main/Domains/TagsMngmt/SaveTagsService.cs
> +        return Task.FromResult(tags);
No it doesn't

2024-02-14 16:42 UTC, noah-martey commented on services/main/Domains/TagsMngmt/SaveTagsService.cs
> +        inputTags.ToList().ForEach(async tag =>
Alright

2024-02-14 17:01 UTC, arkhurst commented on services/main/Controllers/Tag.cs
> +    [HttpPost("create/tag")]
thank you boss

2024-02-14 17:03 UTC, arkhurst commented on services/main/Domains/TagsMngmt/SaveTagsService.cs
>      }
i think i've used this before, IEnumerable

2024-02-14 19:27 UTC, Bendomey commented on services/main/Domains/TagsMngmt/SaveTagsService.cs
> +                var newTag = await Create(new CreateTagInput { Name = tag }, "a_user_id");
gotcha gotcha .... I think you can do this and then update where `ResolveTag` is being used ;)

2024-02-15 12:25 UTC, Bendomey requested changes

2024-02-15 12:25 UTC, Bendomey commented on services/main/Controllers/Tag.cs
> +    public async Task<OutputResponse<Models.Tag>> Create([FromBody] CreateTagInput input)
```suggestion
    public OutputResponse<Models.Tag> Create([FromBody] CreateTagInput input)

```

2024-02-15 12:25 UTC, Bendomey commented on services/main/Domains/TagsMngmt/SaveTagsService.cs
> +                var newTag = Create(new CreateTagInput { Name = tag }, "a_user_id");
Could you fix this? expose it as a variable to that function  argument and fix it usages. After this, I'll merge!

2024-06-22 14:09 UTC, closed without merging