Add Waitlist endpoint
Bendomey/project-mfoni pull request #66
Opened 2024-03-09 17:45 UTC by NanaKay007

2024-03-09 18:19 UTC, NanaKay007 commented
do not review yet!

2024-03-09 18:56 UTC, arkhurst reviewed
LGTM, but want to draw your attention to the linting errors

2024-03-09 18:59 UTC, NanaKay007 commented
urghh. would be helpful to have local lint warnings

2024-03-09 20:34 UTC, Bendomey commented
> @arkhurst urghh. would be helpful to have local lint warnings

Sorry, I meant to push a lint command ... I'll work on that today!

2024-03-09 20:36 UTC, NanaKay007 commented
Thank you! Looking forward to it

Best,
Anikuabe Nana Kweku,
Swarthmore Class of 2022
LinkedIn <https://linkedin.com/in/anikuabenana> | Personal Website
<https://anikuabenana.com/>


On Sat, Mar 9, 2024 at 12:34 PM Ben Domey ***@***.***> wrote:

> @arkhurst <https://github.com/arkhurst> urghh. would be helpful to have
> local lint warnings
>
> Sorry, I meant to push a lint command ... I'll work on that today!
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Bendomey/project-mfoni/pull/66#issuecomment-1986969943>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AH2H5JIEKYOEMZUZXVS3VM3YXNW7BAVCNFSM6AAAAABEOITKYKVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTSOBWHE3DSOJUGM>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2024-03-09 20:56 UTC, Bendomey requested changes
The PR looks very good! I learned a couple things ... the use of `ActionResult`. I've been meaning to learn that!

I added a bunch of comments not because your code is not good enough. It's just me explaining some codebase practices and why we do somethings we do!

2024-03-09 20:56 UTC, Bendomey commented on services/main/Configurations/DatabaseCollectionConstants.cs
> +}
We have a habit of keeping all our constants in this file. `services/main/Configurations/AppConstants.cs`

Find an example usage here as well: `services/main/Domains/Auth/AuthService.cs:26`

2024-03-09 20:56 UTC, Bendomey commented on services/main/Controllers/Waitlist.cs
> +    [HttpPost("create")]
```suggestion
    [HttpPost]
```

This will end up creating an endpoint like this `POST {domain}/api/v1/wailists`.

We're currently using the standard api design out there. Some examples

Create: `POST /api/v1/{resource}`, With body
Get All: `GET /api/v1/{resource}?limit=10&skip=1&...`
Get Single: `GET /api/v1/{resource}/:id`
Update: `PATCH /api/v1/{resource}/:id` - With body, of course
Delete: `DELETE /api/v1/{resource}/:id`

2024-03-09 20:56 UTC, Bendomey commented on services/main/Controllers/Waitlist.cs
> +}
```suggestion
 catch (HttpRequestException e)
        {
            // error response
        }
        catch (Exception e)
        {
            this.logger.LogError($"Failed to save waitlist entry into database. Exception: {e}");
            return new StatusCodeResult(500);
        }
    }
}
```
 Also,
- we use `HttpRequestException` to catch any "user defined" errors that we throw in services. This helps us set custom status codes like 400, 422, etc. Frontend heavily makes use of these status codes as well. So once we send the wrong status code, it impacts them as well
- Reason for separating the `Exception` is because we want to catch errors that shouldn't happen; Any error that was out of our control in code. We'll be setting up an error logger like Sentry to send notifications when these errors come up in the future

2024-03-09 20:56 UTC, Bendomey commented on services/main/Domains/WaitlistMngmt/WaitlistService.cs
> +            throw new Exception("Entry already exists.");
From my prev comment, this means we'll change this to 

```suggestion
            throw new HttpRequestException("Entry already exists."); // It's an overloaded method so if you'd want to set the status code to 400, you can easily add it as a new argument. Docs should also help anywho.
```

2024-03-09 20:56 UTC, Bendomey commented on services/main/Controllers/Waitlist.cs
> +    public async Task<ActionResult> AddWaitlistUser([FromBody] WaitlistEntry waitlistEntry)
About typing the body, I think we can leave this but just to put this out there.

We normally like to keep the DB models in the `services/main/Models` directory. Any [DTOs](https://www.okta.com/identity-101/dto/#:~:text=A%20data%20transfer%20object%20(DTO,without%20potentially%20exposing%20sensitive%20information.) used can be added in this directory `services/main/Transformations`


Like I said, for this, we can leave it because it's literally the same structure!

2024-03-09 20:56 UTC, Bendomey commented on services/main/Models/WaitlistEntry.cs
Lastly, it seems like we might be missing some fields on here.

![Screenshot 2024-03-09 at 8 52 33 PM](https://github.com/Bendomey/project-mfoni/assets/41929243/11b4ab76-8b04-4509-9895-d398c00f26e9)

Email is optional. We might want to also check and make sure we have unique phone numbers and not create duplicate records =)

2024-03-09 21:57 UTC, Bendomey commented
> @arkhurst urghh. would be helpful to have local lint warnings

You can run this `dotnet format main.sln` for now.

I'm opening a new PR to handle linting in a different way(So that it's handled automatically).

2024-03-12 11:21 UTC, Bendomey commented
FYI, we need to close waitlist(api+integration) this week. If you won't get margin to finish it this week, I can finish it up! =)

2024-03-12 18:37 UTC, arkhurst approved these changes

2024-03-12 18:41 UTC, merged