Empty state for category
Bendomey/project-mfoni pull request #84
Opened 2024-09-03 14:22 UTC by AceDheGeneral

2024-09-03 16:41 UTC, Bendomey commented
1. CI is failing
2. Could you send screenshots?
3. Could you add ticket to the description of the PR?


thanks

2024-09-03 17:34 UTC, Bendomey requested changes
Did @arkhurst give you this design or you came up with it? It looks like it's "squashed" to one part of the screen. Could you center it  and make it fill the entire page?


Good work!

2024-09-03 17:34 UTC, Bendomey commented on package-lock.json
could we delete this file? I think you should be using `yarn` to install/update your dependencies from here on out :). You'll only see this file when you use `npm` to manage your packages.

2024-09-03 17:34 UTC, Bendomey commented on apps/client/app/modules/explore/index.tsx
> +          <EmptyState ftn={exploreOther} />
What's `ftn`? Also, I don't think we'd need a prop for navigating to `categories` page.🤔 We might end up having a `/categories` page so maybe it could just be a button link with href of `/categories` (route name could be changed in the future.)

2024-09-03 17:34 UTC, Bendomey commented on apps/client/app/modules/explore/index.tsx
> +  }, [categories])
For now, we could just have a boolean somewhere to toggle the rendering of the empty state component. since all this will be determined by an API.

```suggestion
   const isEmpty = false;
```

2024-09-03 17:34 UTC, Bendomey commented on apps/client/app/modules/explore/components/empty-state/index.tsx
> +            It seems like there are no items in the "Detty December" category
```suggestion
            It seems like there are no items in the &quot;Detty December&quot; category
```

2024-09-04 09:09 UTC, AceDheGeneral commented
![commit1](https://github.com/user-attachments/assets/d0129807-709c-4832-9b4b-c0a10f4750e5)
![commit2](https://github.com/user-attachments/assets/e4407bed-5185-4fe4-bb24-2847f69e3f65)

2024-09-04 09:10 UTC, AceDheGeneral commented on package-lock.json
noted

2024-09-04 09:25 UTC, arkhurst requested changes

2024-09-04 09:25 UTC, arkhurst commented on apps/client/app/modules/explore/components/empty-state/index.tsx
> +            It seems like there are no items in the Detty December category
we probably want to make this message dynamic. we can allow this component to accept props "title" & "message" so we can re-use this component several places with different content.

2024-09-05 13:01 UTC, Bendomey commented on apps/client/app/modules/explore/components/empty-state/index.tsx
> +          </span>
We have a button component. Please let's use that instead. That should be the last from me

2024-09-05 15:03 UTC, AceDheGeneral commented
![commit3](https://github.com/user-attachments/assets/3d1d67c2-4b36-46b8-acbf-bd8a0cd4f8a0)

2024-09-05 15:55 UTC, Bendomey approved these changes

2024-09-05 15:56 UTC, merged