feat:: get users, get creator-applications
Bendomey/project-mfoni pull request #91
Opened 2024-09-21 19:38 UTC by EbenDomey

This pull request contains the endpoints for getting creator applications and users by the admin with the appropriate filters

2024-09-22 15:57 UTC, Bendomey requested changes

2024-09-22 15:57 UTC, Bendomey commented on services/main/Controllers/Admin.cs
> +                new Domains.CreateAdminInput { Name = input.Name, Email = input.Email, }
currentAdmin is removed

2024-09-22 15:57 UTC, Bendomey commented on services/main/Controllers/Admin.cs
> +            );
You could create a dto instead. Try not to have more than 2 arguments for a service action(function)

2024-09-22 15:57 UTC, Bendomey commented on services/main/Controllers/Admin.cs
> +                search
^Ditto

That DTO could be used for both

2024-09-22 15:57 UTC, Bendomey commented on services/main/DTOs/SetupAccountInput.cs
> +    [Required]
Not required 🫠

```suggestion
```

2024-09-22 15:57 UTC, Bendomey commented on services/main/Domains/AdminMngmt/SearchAdminService.cs
> +    public async Task<long> CountAdmins(FilterQuery<Models.Admin> queryFilter, string? query)
I don't think you need the `queryFilters` for count actions

2024-09-22 15:57 UTC, Bendomey commented on services/main/Domains/AdminMngmt/SearchAdminService.cs
> +        FilterQuery<Models.User> queryFilter,
```suggestion

```

2024-09-22 15:57 UTC, Bendomey commented on services/main/Domains/AdminMngmt/SearchAdminService.cs
> +    public async Task<List<CreatorApplication>> GetCreators(
```suggestion
    public async Task<List<CreatorApplication>> GetCreatorApplications(

```

2024-09-22 15:57 UTC, Bendomey commented on services/main/Domains/AdminMngmt/SearchAdminService.cs
> +    )
```suggestion
    public async Task<long> CountCreatorApplications(
        string? status
    )

```

2024-09-22 15:57 UTC, Bendomey commented on services/main/Domains/AdminMngmt/SearchAdminService.cs
> +    public async Task<List<Models.User>> GetUsers(
`GetUsers` should be in the user service file not admin service file

2024-09-22 15:57 UTC, Bendomey commented on services/main/Domains/AdminMngmt/SearchAdminService.cs
> +    public async Task<List<CreatorApplication>> GetCreators(
`GetCreators` should be in the creator application service

2024-09-22 15:57 UTC, Bendomey commented on services/main/Transformations/UserTransformer.cs
> +            Role = user.Role!,
why `!` ?

2024-09-24 19:45 UTC, EbenDomey commented on services/main/Transformations/UserTransformer.cs
> +            Role = user.Role!,
i was getting a warning about it being possibly null so I used the (null-forgiving operator) `!` to resolve that warning. Should I remove it?

2024-09-24 20:25 UTC, Bendomey commented on services/main/Transformations/UserTransformer.cs
> +            Role = user.Role!,
Weirdddd. I'll have to investigate because there must be something wrong somewhere. Using `!` just takes away the error but doesn't really solve the core problem 😆

It just promotes the error from build time to runtime in somecases . Add a todo in there for me to take a look later. I'll approve if the other changes look good!

2024-09-24 20:29 UTC, EbenDomey commented on services/main/Transformations/UserTransformer.cs
> +            Role = user.Role!,
Alright. I thought it was intentional on your side. I suggest you check the `User` model you'll find it there

2024-09-24 22:32 UTC, Bendomey requested changes
just 2 changes and we should be good!

2024-09-24 22:32 UTC, Bendomey commented on services/main/Domains/AdminMngmt/SearchAdminService.cs
> +
Oversight?

2024-09-24 22:32 UTC, Bendomey commented on services/main/Domains/AdminMngmt/dto.cs
> +}
Users dto in admin service ?

2024-09-25 13:29 UTC, merged