chore:update pricing plans
Bendomey/project-mfoni pull request #94
Opened 2024-10-25 13:39 UTC by adu-yeboah

2024-10-25 17:10 UTC, arkhurst requested changes

2024-10-25 17:10 UTC, arkhurst commented on apps/client/app/modules/landing-page/components/pricing/index.tsx
>      priceMonthly: '$9.99',
I believe we put the correct pricing there. can we update where neccessary

2024-10-26 05:19 UTC, adu-yeboah commented
the price was not provided since it wasn't part of the task

2024-10-26 05:34 UTC, adu-yeboah commented
![143](https://github.com/user-attachments/assets/20d0b01d-0af5-448e-a602-b2dc79e21510)

2024-10-26 14:26 UTC, adu-yeboah commented
![Uploading Capture.JPG…]()

2024-10-26 15:42 UTC, Bendomey approved these changes

2024-10-26 15:43 UTC, arkhurst approved these changes

2024-10-26 15:44 UTC, merged